In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('data_tocube.csv')

In [3]:
df.head(1)

Unnamed: 0                 GADE Platform  Hours    whyplay   League  \
0           1  Extremely difficult       PC     60  improving  Diamond   

   streams  Narcissism Gender  Age  ...       Degree Birthplace Residence  \
0       10           3   Male   24  ...  High School    Germany   Germany   

                                           Playstyle GAD_T  SWL_T  SPIN_T  \
0  Multiplayer - online - with online acquaintanc...    15      9      37   

  GAD_cat                 SWL_cat  SPIN_cat  
0  Severe  Extremely dissastified  Moderate  

[1 rows x 21 columns]

In [4]:
df2 = df[['League','Degree','whyplay','Age','GAD_T']]

In [5]:
df2.to_csv('categorical.csv',index=False)

In [6]:
df3 = pd.read_csv('categorical.csv')

In [7]:
df3.head(2)

League       Degree     whyplay  Age  GAD_T
0  Diamond  High School   improving   24     15
1   Bronze     Bachelor  having fun   36      5

In [8]:
df3.dtypes

League     object
Degree     object
whyplay    object
Age         int64
GAD_T       int64
dtype: object

In [190]:
df3.select_dtypes(['object'])

League       Degree     whyplay
0     Diamond  High School   improving
1      Bronze     Bachelor  having fun
2        Gold  High School     winning
3        Gold       Master  having fun
4        Gold  High School  having fun
...       ...          ...         ...
8969     Gold       Master    relaxing
8970   Silver         None   improving
8971   Silver  High School  having fun
8972     Gold  High School  having fun
8973  Diamond  High School   improving

[8974 rows x 3 columns]

In [156]:
arr = df.to_numpy()

In [157]:
arr

array([[60, 15],
       [ 5,  5],
       [ 6,  2],
       ...,
       [30,  6],
       [20,  0],
       [15,  2]])

In [165]:
dims = 0

In [166]:
arr2 = sorted(arr, key=lambda a: a[dims])

In [168]:
dim = [i[1] for i in arr2]

In [170]:
np.mean(dim)

5.384778248272788

In [160]:
a = arr

In [176]:
arr2[0][0]

0

In [198]:
hash(tuple(arr2[0]))

7204814214171964562

In [199]:
arr2[0]

array([0, 2])

In [200]:
b = np.array([2,0])

In [201]:
b

array([2, 0])

In [202]:
hash(tuple(b))

4685526799349444076

In [203]:
set(arr2[0]) == set(b)

True

In [204]:
c = [[2,0],[3,0],[1,0]]

In [205]:
[2,0] in c

True

In [206]:
[0,2] in c

False