In [101]:
import numpy as np
import pandas as pd

In [102]:
df = pd.read_csv('datos.csv')

In [107]:
df = pd.read_csv('data_tocube.csv')

In [110]:
df = df[['Hours','Age']]

In [111]:
df.to_csv('Hours_age.csv',index=False)

In [136]:
df = pd.read_csv('Hours_age.csv')

In [137]:
df.head(5)

Hours  Age
0     60   24
1      5   36
2      6   22
3      7   25
4      7   21

In [138]:
arr = df.to_numpy()

In [139]:
arr

array([[60, 24],
       [ 5, 36],
       [ 6, 22],
       ...,
       [30, 21],
       [20, 19],
       [15, 19]])

In [143]:
dim = [i[0] for i in arr2]

In [145]:
np.mean(dim)

21.566525518163584

In [121]:
a = arr

In [141]:
arr2 = sorted(a, key=lambda a: a[dim])

In [140]:
dim = 0

In [142]:
arr2

[array([ 0, 20]),
 array([ 0, 27]),
 array([ 0, 18]),
 array([ 0, 19]),
 array([ 0, 20]),
 array([ 1, 25]),
 array([ 1, 19]),
 array([ 1, 18]),
 array([ 1, 18]),
 array([ 1, 23]),
 array([ 1, 23]),
 array([ 1, 19]),
 array([ 1, 22]),
 array([ 1, 18]),
 array([ 1, 18]),
 array([ 1, 22]),
 array([ 1, 20]),
 array([ 2, 25]),
 array([ 2, 38]),
 array([ 2, 19]),
 array([ 2, 18]),
 array([ 2, 33]),
 array([ 2, 21]),
 array([ 2, 20]),
 array([ 2, 19]),
 array([ 2, 20]),
 array([ 2, 23]),
 array([ 2, 25]),
 array([ 2, 22]),
 array([ 2, 19]),
 array([ 2, 20]),
 array([ 2, 21]),
 array([ 2, 20]),
 array([ 2, 18]),
 array([ 2, 20]),
 array([ 2, 20]),
 array([ 2, 22]),
 array([ 2, 20]),
 array([ 2, 22]),
 array([ 2, 20]),
 array([ 2, 23]),
 array([ 2, 18]),
 array([ 2, 20]),
 array([ 2, 21]),
 array([ 2, 18]),
 array([ 2, 18]),
 array([ 2, 21]),
 array([ 2, 18]),
 array([ 2, 18]),
 array([ 2, 19]),
 array([ 2, 23]),
 array([ 2, 19]),
 array([ 2, 22]),
 array([ 2, 18]),
 array([ 2, 20]),
 array([ 2

In [146]:
len(arr2)

8974