In [101]:
import numpy as np
import pandas as pd

In [102]:
df = pd.read_csv('datos.csv')

In [149]:
df = pd.read_csv('data_tocube.csv')

In [151]:
df = df[['Hours','GAD_T']]

In [152]:
df.to_csv('hours_gad.csv',index=False)

In [154]:
df = pd.read_csv('hours_gad.csv')

In [155]:
df.head(5)

Hours  GAD_T
0     60     15
1      5      5
2      6      2
3      7      1
4      7      7

In [156]:
arr = df.to_numpy()

In [157]:
arr

array([[60, 15],
       [ 5,  5],
       [ 6,  2],
       ...,
       [30,  6],
       [20,  0],
       [15,  2]])

In [165]:
dims = 0

In [166]:
arr2 = sorted(arr, key=lambda a: a[dims])

In [168]:
dim = [i[1] for i in arr2]

In [170]:
np.mean(dim)

5.384778248272788

In [160]:
a = arr

In [163]:
arr2

[array([ 0, 20]),
 array([ 0, 27]),
 array([ 0, 18]),
 array([ 0, 19]),
 array([ 0, 20]),
 array([ 1, 25]),
 array([ 1, 19]),
 array([ 1, 18]),
 array([ 1, 18]),
 array([ 1, 23]),
 array([ 1, 23]),
 array([ 1, 19]),
 array([ 1, 22]),
 array([ 1, 18]),
 array([ 1, 18]),
 array([ 1, 22]),
 array([ 1, 20]),
 array([ 2, 25]),
 array([ 2, 38]),
 array([ 2, 19]),
 array([ 2, 18]),
 array([ 2, 33]),
 array([ 2, 21]),
 array([ 2, 20]),
 array([ 2, 19]),
 array([ 2, 20]),
 array([ 2, 23]),
 array([ 2, 25]),
 array([ 2, 22]),
 array([ 2, 19]),
 array([ 2, 20]),
 array([ 2, 21]),
 array([ 2, 20]),
 array([ 2, 18]),
 array([ 2, 20]),
 array([ 2, 20]),
 array([ 2, 22]),
 array([ 2, 20]),
 array([ 2, 22]),
 array([ 2, 20]),
 array([ 2, 23]),
 array([ 2, 18]),
 array([ 2, 20]),
 array([ 2, 21]),
 array([ 2, 18]),
 array([ 2, 18]),
 array([ 2, 21]),
 array([ 2, 18]),
 array([ 2, 18]),
 array([ 2, 19]),
 array([ 2, 23]),
 array([ 2, 19]),
 array([ 2, 22]),
 array([ 2, 18]),
 array([ 2, 20]),
 array([ 2

In [176]:
arr2[0][0]

0