In [101]:
import numpy as np
import pandas as pd

In [102]:
df = pd.read_csv('datos.csv')

In [183]:
df = pd.read_csv('data_tocube.csv')

In [151]:
df = df[['Hours','GAD_T']]

In [152]:
df.to_csv('hours_gad.csv',index=False)

In [154]:
df = pd.read_csv('hours_gad.csv')

In [185]:
df2 = df[['League','Degree','whyplay','GAD_T']]

In [186]:
df2.to_csv('categorical.csv',index=False)

In [187]:
df3 = pd.read_csv('categorical.csv')

In [188]:
df3.head(2)

League       Degree     whyplay  GAD_T
0  Diamond  High School   improving     15
1   Bronze     Bachelor  having fun      5

In [189]:
df3.dtypes

League     object
Degree     object
whyplay    object
GAD_T       int64
dtype: object

In [190]:
df3.select_dtypes(['object'])

League       Degree     whyplay
0     Diamond  High School   improving
1      Bronze     Bachelor  having fun
2        Gold  High School     winning
3        Gold       Master  having fun
4        Gold  High School  having fun
...       ...          ...         ...
8969     Gold       Master    relaxing
8970   Silver         None   improving
8971   Silver  High School  having fun
8972     Gold  High School  having fun
8973  Diamond  High School   improving

[8974 rows x 3 columns]

In [156]:
arr = df.to_numpy()

In [157]:
arr

array([[60, 15],
       [ 5,  5],
       [ 6,  2],
       ...,
       [30,  6],
       [20,  0],
       [15,  2]])

In [165]:
dims = 0

In [166]:
arr2 = sorted(arr, key=lambda a: a[dims])

In [168]:
dim = [i[1] for i in arr2]

In [170]:
np.mean(dim)

5.384778248272788

In [160]:
a = arr

In [176]:
arr2[0][0]

0

In [198]:
hash(tuple(arr2[0]))

7204814214171964562

In [199]:
arr2[0]

array([0, 2])

In [200]:
b = np.array([2,0])

In [201]:
b

array([2, 0])

In [202]:
hash(tuple(b))

4685526799349444076

In [203]:
set(arr2[0]) == set(b)

True

In [204]:
c = [[2,0],[3,0],[1,0]]

In [205]:
[2,0] in c

True

In [206]:
[0,2] in c

False